// <auto-generated />
using System;
using EmitGestion.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EmitGestion.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260712092229_Batiment_Retrait_Adresse")]
    partial class Batiment_Retrait_Adresse
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EmitGestion.Api.Models.AnneeAcademique", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateOnly>("DateDebut")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DateFin")
                        .HasColumnType("date");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Libelle")
                        .IsUnique();

                    b.ToTable("AnneesAcademiques");
                });

            modelBuilder.Entity("EmitGestion.Api.Models.Batiment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Batiments");
                });

            modelBuilder.Entity("EmitGestion.Api.Models.DisponibiliteEnseignant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Commentaire")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<DateOnly?>("DateDebut")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DateFin")
                        .HasColumnType("date");

                    b.Property<bool>("Disponible")
                        .HasColumnType("boolean");

                    b.Property<int>("EnseignantId")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("HeureDebut")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("HeureFin")
                        .HasColumnType("time without time zone");

                    b.Property<int>("JourSemaine")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EnseignantId");

                    b.ToTable("Disponibilites");
                });

            modelBuilder.Entity("EmitGestion.Api.Models.Enseignant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("Grade")
                        .HasColumnType("integer");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Prenoms")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Telephone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.ToTable("Enseignants");
                });

            modelBuilder.Entity("EmitGestion.Api.Models.Etudiant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnneeAcademiqueId")
                        .HasColumnType("integer");

                    b.Property<string>("Cin")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateOnly?>("DateNaissance")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("FiliereId")
                        .HasColumnType("integer");

                    b.Property<int?>("GroupeId")
                        .HasColumnType("integer");

                    b.Property<string>("Matricule")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("NiveauId")
                        .HasColumnType("integer");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("ParcoursId")
                        .HasColumnType("integer");

                    b.Property<string>("Prenoms")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("Sexe")
                        .HasColumnType("integer");

                    b.Property<int>("Statut")
                        .HasColumnType("integer");

                    b.Property<string>("Telephone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("AnneeAcademiqueId");

                    b.HasIndex("FiliereId");

                    b.HasIndex("GroupeId");

                    b.HasIndex("Matricule")
                        .IsUnique();

                    b.HasIndex("NiveauId");

                    b.HasIndex("ParcoursId");

                    b.ToTable("Etudiants");
                });

            modelBuilder.Entity("EmitGestion.Api.Models.Examen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnneeAcademiqueId")
                        .HasColumnType("integer");

                    b.Property<string>("ChefScolarite")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("EnseignantId")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("HeureDebut")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("HeureFin")
                        .HasColumnType("time without time zone");

                    b.Property<int>("MatiereId")
                        .HasColumnType("integer");

                    b.Property<int>("Session")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AnneeAcademiqueId");

                    b.HasIndex("EnseignantId");

                    b.HasIndex("MatiereId");

                    b.ToTable("Examens");
                });

            modelBuilder.Entity("EmitGestion.Api.Models.ExamenSalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ExamenId")
                        .HasColumnType("integer");

                    b.Property<int>("SalleId")
                        .HasColumnType("integer");

                    b.Property<string>("Surveillant1")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Surveillant2")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Surveillant3")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("ExamenId");

                    b.HasIndex("SalleId");

                    b.ToTable("ExamenSalles");
                });

            modelBuilder.Entity("EmitGestion.Api.Models.Filiere", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Archivee")
                        .HasColumnType("boolean");

                    b.Property<string>("CodeFiliere")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("LettreSpecifique")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("CodeFiliere")
                        .IsUnique();

                    b.HasIndex("LettreSpecifique")
                        .IsUnique();

                    b.ToTable("Filieres");
                });

            modelBuilder.Entity("EmitGestion.Api.Models.Groupe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FiliereId")
                        .HasColumnType("integer");

                    b.Property<int>("NiveauId")
                        .HasColumnType("integer");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("ParcoursId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FiliereId");

                    b.HasIndex("NiveauId");

                    b.HasIndex("ParcoursId");

                    b.ToTable("Groupes");
                });

            modelBuilder.Entity("EmitGestion.Api.Models.Matiere", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CodeMatiere")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Coefficient")
                        .HasColumnType("integer");

                    b.Property<int?>("CreditsEcts")
                        .HasColumnType("integer");

                    b.Property<int>("FiliereId")
                        .HasColumnType("integer");

                    b.Property<int>("NiveauId")
                        .HasColumnType("integer");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int?>("ParcoursId")
                        .HasColumnType("integer");

                    b.Property<int>("Semestre")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CodeMatiere")
                        .IsUnique();

                    b.HasIndex("FiliereId");

                    b.HasIndex("NiveauId");

                    b.HasIndex("ParcoursId");

                    b.ToTable("Matieres");
                });

            modelBuilder.Entity("EmitGestion.Api.Models.Niveau", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Ordre")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Niveaux");
                });

            modelBuilder.Entity("EmitGestion.Api.Models.Parcours", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FiliereId")
                        .HasColumnType("integer");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("FiliereId");

                    b.ToTable("Parcours");
                });

            modelBuilder.Entity("EmitGestion.Api.Models.Salle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BatimentId")
                        .HasColumnType("integer");

                    b.Property<int>("Capacite")
                        .HasColumnType("integer");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Numero")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("TypeSalle")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BatimentId");

                    b.ToTable("Salles");
                });

            modelBuilder.Entity("EmitGestion.Api.Models.Seance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnneeAcademiqueId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("DateCours")
                        .HasColumnType("date");

                    b.Property<int>("EnseignantId")
                        .HasColumnType("integer");

                    b.Property<int>("GroupeId")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("HeureDebut")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("HeureFin")
                        .HasColumnType("time without time zone");

                    b.Property<int>("MatiereId")
                        .HasColumnType("integer");

                    b.Property<int>("SalleId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SerieId")
                        .HasColumnType("uuid");

                    b.Property<int>("TypeSeance")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AnneeAcademiqueId");

                    b.HasIndex("EnseignantId");

                    b.HasIndex("GroupeId");

                    b.HasIndex("MatiereId");

                    b.HasIndex("SalleId");

                    b.ToTable("Seances");
                });

            modelBuilder.Entity("EmitGestion.Api.Models.Utilisateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Actif")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EnseignantId")
                        .HasColumnType("integer");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("MotDePasseHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomComplet")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EnseignantId");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("Utilisateurs");
                });

            modelBuilder.Entity("EnseignantMatiere", b =>
                {
                    b.Property<int>("EnseignantsId")
                        .HasColumnType("integer");

                    b.Property<int>("MatieresId")
                        .HasColumnType("integer");

                    b.HasKey("EnseignantsId", "MatieresId");

                    b.HasIndex("MatieresId");

                    b.ToTable("EnseignantMatieres", (string)null);
                });

            modelBuilder.Entity("NiveauParcours", b =>
                {
                    b.Property<int>("NiveauxId")
                        .HasColumnType("integer");

                    b.Property<int>("ParcoursId")
                        .HasColumnType("integer");

                    b.HasKey("NiveauxId", "ParcoursId");

                    b.HasIndex("ParcoursId");

                    b.ToTable("ParcoursNiveaux", (string)null);
                });

            modelBuilder.Entity("EmitGestion.Api.Models.DisponibiliteEnseignant", b =>
                {
                    b.HasOne("EmitGestion.Api.Models.Enseignant", "Enseignant")
                        .WithMany("Disponibilites")
                        .HasForeignKey("EnseignantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Enseignant");
                });

            modelBuilder.Entity("EmitGestion.Api.Models.Etudiant", b =>
                {
                    b.HasOne("EmitGestion.Api.Models.AnneeAcademique", "AnneeAcademique")
                        .WithMany("Etudiants")
                        .HasForeignKey("AnneeAcademiqueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EmitGestion.Api.Models.Filiere", "Filiere")
                        .WithMany("Etudiants")
                        .HasForeignKey("FiliereId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EmitGestion.Api.Models.Groupe", "Groupe")
                        .WithMany("Etudiants")
                        .HasForeignKey("GroupeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EmitGestion.Api.Models.Niveau", "Niveau")
                        .WithMany("Etudiants")
                        .HasForeignKey("NiveauId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EmitGestion.Api.Models.Parcours", "Parcours")
                        .WithMany("Etudiants")
                        .HasForeignKey("ParcoursId");

                    b.Navigation("AnneeAcademique");

                    b.Navigation("Filiere");

                    b.Navigation("Groupe");

                    b.Navigation("Niveau");

                    b.Navigation("Parcours");
                });

            modelBuilder.Entity("EmitGestion.Api.Models.Examen", b =>
                {
                    b.HasOne("EmitGestion.Api.Models.AnneeAcademique", "AnneeAcademique")
                        .WithMany()
                        .HasForeignKey("AnneeAcademiqueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EmitGestion.Api.Models.Enseignant", "Enseignant")
                        .WithMany()
                        .HasForeignKey("EnseignantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EmitGestion.Api.Models.Matiere", "Matiere")
                        .WithMany()
                        .HasForeignKey("MatiereId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AnneeAcademique");

                    b.Navigation("Enseignant");

                    b.Navigation("Matiere");
                });

            modelBuilder.Entity("EmitGestion.Api.Models.ExamenSalle", b =>
                {
                    b.HasOne("EmitGestion.Api.Models.Examen", "Examen")
                        .WithMany("Salles")
                        .HasForeignKey("ExamenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EmitGestion.Api.Models.Salle", "Salle")
                        .WithMany()
                        .HasForeignKey("SalleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Examen");

                    b.Navigation("Salle");
                });

            modelBuilder.Entity("EmitGestion.Api.Models.Groupe", b =>
                {
                    b.HasOne("EmitGestion.Api.Models.Filiere", "Filiere")
                        .WithMany("Groupes")
                        .HasForeignKey("FiliereId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EmitGestion.Api.Models.Niveau", "Niveau")
                        .WithMany("Groupes")
                        .HasForeignKey("NiveauId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EmitGestion.Api.Models.Parcours", "Parcours")
                        .WithMany("Groupes")
                        .HasForeignKey("ParcoursId");

                    b.Navigation("Filiere");

                    b.Navigation("Niveau");

                    b.Navigation("Parcours");
                });

            modelBuilder.Entity("EmitGestion.Api.Models.Matiere", b =>
                {
                    b.HasOne("EmitGestion.Api.Models.Filiere", "Filiere")
                        .WithMany("Matieres")
                        .HasForeignKey("FiliereId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EmitGestion.Api.Models.Niveau", "Niveau")
                        .WithMany("Matieres")
                        .HasForeignKey("NiveauId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EmitGestion.Api.Models.Parcours", "Parcours")
                        .WithMany("Matieres")
                        .HasForeignKey("ParcoursId");

                    b.Navigation("Filiere");

                    b.Navigation("Niveau");

                    b.Navigation("Parcours");
                });

            modelBuilder.Entity("EmitGestion.Api.Models.Parcours", b =>
                {
                    b.HasOne("EmitGestion.Api.Models.Filiere", "Filiere")
                        .WithMany("Parcours")
                        .HasForeignKey("FiliereId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Filiere");
                });

            modelBuilder.Entity("EmitGestion.Api.Models.Salle", b =>
                {
                    b.HasOne("EmitGestion.Api.Models.Batiment", "Batiment")
                        .WithMany("Salles")
                        .HasForeignKey("BatimentId");

                    b.Navigation("Batiment");
                });

            modelBuilder.Entity("EmitGestion.Api.Models.Seance", b =>
                {
                    b.HasOne("EmitGestion.Api.Models.AnneeAcademique", "AnneeAcademique")
                        .WithMany("Seances")
                        .HasForeignKey("AnneeAcademiqueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EmitGestion.Api.Models.Enseignant", "Enseignant")
                        .WithMany("Seances")
                        .HasForeignKey("EnseignantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EmitGestion.Api.Models.Groupe", "Groupe")
                        .WithMany("Seances")
                        .HasForeignKey("GroupeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EmitGestion.Api.Models.Matiere", "Matiere")
                        .WithMany("Seances")
                        .HasForeignKey("MatiereId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EmitGestion.Api.Models.Salle", "Salle")
                        .WithMany("Seances")
                        .HasForeignKey("SalleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AnneeAcademique");

                    b.Navigation("Enseignant");

                    b.Navigation("Groupe");

                    b.Navigation("Matiere");

                    b.Navigation("Salle");
                });

            modelBuilder.Entity("EmitGestion.Api.Models.Utilisateur", b =>
                {
                    b.HasOne("EmitGestion.Api.Models.Enseignant", "Enseignant")
                        .WithMany()
                        .HasForeignKey("EnseignantId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Enseignant");
                });

            modelBuilder.Entity("EnseignantMatiere", b =>
                {
                    b.HasOne("EmitGestion.Api.Models.Enseignant", null)
                        .WithMany()
                        .HasForeignKey("EnseignantsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EmitGestion.Api.Models.Matiere", null)
                        .WithMany()
                        .HasForeignKey("MatieresId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("NiveauParcours", b =>
                {
                    b.HasOne("EmitGestion.Api.Models.Niveau", null)
                        .WithMany()
                        .HasForeignKey("NiveauxId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EmitGestion.Api.Models.Parcours", null)
                        .WithMany()
                        .HasForeignKey("ParcoursId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("EmitGestion.Api.Models.AnneeAcademique", b =>
                {
                    b.Navigation("Etudiants");

                    b.Navigation("Seances");
                });

            modelBuilder.Entity("EmitGestion.Api.Models.Batiment", b =>
                {
                    b.Navigation("Salles");
                });

            modelBuilder.Entity("EmitGestion.Api.Models.Enseignant", b =>
                {
                    b.Navigation("Disponibilites");

                    b.Navigation("Seances");
                });

            modelBuilder.Entity("EmitGestion.Api.Models.Examen", b =>
                {
                    b.Navigation("Salles");
                });

            modelBuilder.Entity("EmitGestion.Api.Models.Filiere", b =>
                {
                    b.Navigation("Etudiants");

                    b.Navigation("Groupes");

                    b.Navigation("Matieres");

                    b.Navigation("Parcours");
                });

            modelBuilder.Entity("EmitGestion.Api.Models.Groupe", b =>
                {
                    b.Navigation("Etudiants");

                    b.Navigation("Seances");
                });

            modelBuilder.Entity("EmitGestion.Api.Models.Matiere", b =>
                {
                    b.Navigation("Seances");
                });

            modelBuilder.Entity("EmitGestion.Api.Models.Niveau", b =>
                {
                    b.Navigation("Etudiants");

                    b.Navigation("Groupes");

                    b.Navigation("Matieres");
                });

            modelBuilder.Entity("EmitGestion.Api.Models.Parcours", b =>
                {
                    b.Navigation("Etudiants");

                    b.Navigation("Groupes");

                    b.Navigation("Matieres");
                });

            modelBuilder.Entity("EmitGestion.Api.Models.Salle", b =>
                {
                    b.Navigation("Seances");
                });
#pragma warning restore 612, 618
        }
    }
}
